In [1]:
import numpy as np
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [2]:
np.ones(shape=(3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [3]:
np.full(shape=(4, 2), fill_value=5)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [4]:
print(np.random.rand(3, 2))
print(np.random.randn(3, 2))

[[0.20226738 0.81124791]
 [0.94763164 0.28855327]
 [0.15461205 0.68857619]]
[[-1.11136903 -0.35171436]
 [-0.60325377  2.14141226]
 [ 1.06111162 -0.27562081]]
