In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [5]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [6]:
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [8]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [9]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [10]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [11]:
optimizer = optim.SGD([W,b], lr=0.01)
optimizer.zero_grad()
cost.backward()
optimizer.step()

In [13]:
nb_epochs = 1999
for epoch in range(nb_epochs+1):
    hypothesis = x_train * W + b # 예측값 계산
    cost = torch.mean((hypothesis - y_train) ** 2) # cost function
    
    # cost function을 통해 H(x) 개선
    optimizer.zero_grad()
    cost.backward() # 오차역전파
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch: {:4d}/{} W:{:.3f}, b: {:.3f}, Cost: {:.6f}'.format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch:    0/1999 W:0.500, b: 0.214, Cost: 11.691541
Epoch:  100/1999 W:1.747, b: 0.575, Cost: 0.047709
Epoch:  200/1999 W:1.801, b: 0.452, Cost: 0.029481
Epoch:  300/1999 W:1.844, b: 0.356, Cost: 0.018218
Epoch:  400/1999 W:1.877, b: 0.279, Cost: 0.011257
Epoch:  500/1999 W:1.903, b: 0.220, Cost: 0.006956
Epoch:  600/1999 W:1.924, b: 0.173, Cost: 0.004299
Epoch:  700/1999 W:1.940, b: 0.136, Cost: 0.002656
Epoch:  800/1999 W:1.953, b: 0.107, Cost: 0.001641
Epoch:  900/1999 W:1.963, b: 0.084, Cost: 0.001014
Epoch: 1000/1999 W:1.971, b: 0.066, Cost: 0.000627
Epoch: 1100/1999 W:1.977, b: 0.052, Cost: 0.000387
Epoch: 1200/1999 W:1.982, b: 0.041, Cost: 0.000239
Epoch: 1300/1999 W:1.986, b: 0.032, Cost: 0.000148
Epoch: 1400/1999 W:1.989, b: 0.025, Cost: 0.000091
Epoch: 1500/1999 W:1.991, b: 0.020, Cost: 0.000056
Epoch: 1600/1999 W:1.993, b: 0.016, Cost: 0.000035
Epoch: 1700/1999 W:1.995, b: 0.012, Cost: 0.000022
Epoch: 1800/1999 W:1.996, b: 0.010, Cost: 0.000013
Epoch: 1900/1999 W:1.997, b: 0