In [50]:
import numpy as np
array1 = np.array([1, 2, 3]) # 1차원 ndarray
array2 = np.array([[1, 2, 3],
                   [2, 3, 4]]) # 2차원 ndarray

In [51]:
array1.shape

(3,)

In [52]:
array1.ndim

1

In [53]:
array2.shape

(2, 3)

In [54]:
array2.ndim

2

In [55]:
array1.dtype

dtype('int32')

In [56]:
array2.dtype

dtype('int32')

In [57]:
array2 = array2.astype('float')

In [58]:
array2.dtype

dtype('float64')

In [59]:
array1 = array1.astype(np.float64)

In [60]:
array1.dtype

dtype('float64')

In [61]:
list1 = [1, 2, 3]
print(f'list1 type: {type(list1)}')
array1 = np.array(list1)
print(f'array1 type: {type(array1)}')
print('array1의 형태: ', array1.shape)
print(array1)

list1 type: <class 'list'>
array1 type: <class 'numpy.ndarray'>
array1의 형태:  (3,)
[1 2 3]


In [62]:
array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print(f'array2 type: {type(array2)}')
print(f'array2의 형태: {array2.shape}')

array2 type: <class 'numpy.ndarray'>
array2의 형태: (2, 3)


In [63]:
array3 = np.array([
    [1, 2, 3]
    ])
print(type(array3))

<class 'numpy.ndarray'>


In [64]:
print(array3.shape)

(1, 3)


In [65]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [66]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [67]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3) # 자동 형변환
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [68]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype(np.float64)
print(array_float, array_float.dtype)


[1. 2. 3.] float64


In [69]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [70]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


In [71]:
array1 = np.arange(10)
array2 = np.zeros((3, 2), dtype='int32')
array3 = np.ones((3, 2))

In [72]:
print(array1, array2, array3)

[0 1 2 3 4 5 6 7 8 9] [[0 0]
 [0 0]
 [0 0]] [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [73]:
array1 = array1.reshape(2, 5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
array2 = array2.reshape(-1, 3)
array2

array([[0, 0, 0],
       [0, 0, 0]])

In [75]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [76]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [77]:
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [78]:
array1 = np.arange(10)
print(f'array1: \n {array1}')

array2 = array1.reshape(5, 2)
print(f'array2:\n {array2}')

array1: 
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [79]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print(array2)

array3 = array1.reshape(5, -1)
print(array3.shape)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
(5, 2)


In [80]:
array1 = np.arange(10)
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print(f'array3\n {array3d.tolist()}')
print(array3d)

array5 = array3d.reshape(-1, 1)
print(array5.tolist())
print(array5.shape)
array6 = array1.reshape(-1 , 1)
print(array6.tolist())
print(array6.shape)

array3
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)


In [81]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array1[1:9]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
array1[1][1]
array1[:1][:1]
array1[:2, :2][0]

array([1, 2])

In [83]:
array1 = np.array([3, 5, 7])
array1[[0, 2]]

array([3, 7])

In [84]:
array1d = np.arange(start=0, stop=10)
array1d[array1d > 5]

array([6, 7, 8, 9])

In [85]:
array1d = np.arange(start=1, stop=10)
target=[]
for i in range(0, 9):
    if array1d[i] > 5:
        target.append(array1d[i])

array_selected = np.array(target)

In [87]:
# 1에서부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print(array1)
value = array1[2]
print(value)
print(type(value))

[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int32'>


In [88]:
print(array1[-1])
print(array1[-2])

9
8


In [89]:
array1[0] = 9
array1[8] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


In [92]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array1d)
print(array2d)
print(array2d[0,0])
print(array2d[0, 1])
print(array2d[1,0])
print(array2d[2,2])

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


In [93]:
array1 = np.arange(start=1, stop=10)
print(array1)
array3 = array1[0:3]
print(array3)

[1 2 3 4 5 6 7 8 9]
[1 2 3]


In [94]:
print(type(array3))

<class 'numpy.ndarray'>


In [95]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [96]:
array3.shape

(3,)

In [104]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:,:])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [110]:
print(array2d[0][0])
print(array2d[1][1])

1
5


In [112]:
print(array2d[0])
print(array2d[1])
print(array2d[0].shape)
print(array2d[1].shape)

[1 2 3]
[4 5 6]
(3,)
(3,)


In [117]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

array3 = array2d[[0, 1], 2]
print(array3)
print(array3.tolist())
array4 = array2d[[0,1], 0:2]
print(array4)
print(array4.tolist())
array5 = array2d[[0,1]]
print(array5)
print(array5.tolist())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[3, 6]
[[1 2]
 [4 5]]
[[1, 2], [4, 5]]
[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


In [119]:
array1d = np.arange(1, 10)
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


In [120]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [121]:
val = array1d > 5
print(val, type(val), val.shape)

[False False False False False  True  True  True  True] <class 'numpy.ndarray'> (9,)


In [123]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print(array3)

[6 7 8 9]


In [124]:
array1d = np.arange(1, 10)
target = []
# 불린 인덱스를 사용하지 않았을 경우
for i in range(array1d.size):
    if array1d[i] > 5:
        target.append(array1d[i])

print(target)

[6, 7, 8, 9]


In [125]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print(array4)

[6 7 8 9]


In [132]:
array1 = np.array([1, 2,5, -1, -5, 10, 6])
print(array1)
array1 = np.sort(array1)
print(array1)
np.ndarray.sort(array1, 0)
print(array1)

[ 1  2  5 -1 -5 10  6]
[-5 -1  1  2  5  6 10]
[-5 -1  1  2  5  6 10]


In [134]:
array1 = np.array([[1, 2, 3],
                   [-2, -3, -4]])
array2 = np.sort(array1)
print(array2)
array1 = np.array([3, 1, 9, 5])
index = np.argsort(array1)
print(index)
print(array1)

[[ 1  2  3]
 [-4 -3 -2]]
[1 0 3 2]
[3 1 9 5]


In [136]:
org_array = np.array([3, 1, 9, 5])
print(org_array)
sort_array1 = np.sort(org_array)
print(sort_array1)
print(org_array)
sort_array2 = org_array.sort()
print(sort_array2)
print(org_array)

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]


In [138]:
sort_array1_desc = np.sort(org_array)[ : :-1]
print(sort_array1_desc)

[9 5 3 1]


In [141]:
array2d = np.array([[8, 12],
                    [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [142]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[1 0 3 2]


In [143]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print(sort_indices_desc)

[2 3 0 1]


In [145]:
import numpy as np

name_array = np.array(['John', 'Mike', "Sarah", 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])
sort_indices_asc = np.argsort(score_array)

print(sort_indices_asc)
print(name_array[sort_indices_asc])



[0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [146]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8],
                   [9, 10],
                   [11, 12]])
print(array1.dot(array2))

[[ 58  64]
 [139 154]]


In [148]:
array1 = np.transpose(array1)
print(array1)

[[1 4]
 [2 5]
 [3 6]]


In [149]:
A = np.array([[1, 2],
              [3, 4]])
np.transpose(A).transpose()
print(A)

[[1 2]
 [3 4]]
