In [1]:
import numpy as np
array1 = np.array([1, 2, 3]) # 1차원 ndarray
array2 = np.array([[1, 2, 3],
                   [2, 3, 4]]) # 2차원 ndarray

In [2]:
array1.shape

(3,)

In [3]:
array1.ndim

1

In [4]:
array2.shape

(2, 3)

In [5]:
array2.ndim

2

In [8]:
array1.dtype

dtype('int32')

In [9]:
array2.dtype

dtype('int32')

In [12]:
array2 = array2.astype('float')

In [13]:
array2.dtype

dtype('float64')

In [14]:
array1 = array1.astype(np.float64)

In [15]:
array1.dtype

dtype('float64')

In [18]:
list1 = [1, 2, 3]
print(f'list1 type: {type(list1)}')
array1 = np.array(list1)
print(f'array1 type: {type(array1)}')
print('array1의 형태: ', array1.shape)
print(array1)

list1 type: <class 'list'>
array1 type: <class 'numpy.ndarray'>
array1의 형태:  (3,)
[1 2 3]


In [19]:
array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print(f'array2 type: {type(array2)}')
print(f'array2의 형태: {array2.shape}')

array2 type: <class 'numpy.ndarray'>
array2의 형태: (2, 3)


In [20]:
array3 = np.array([
    [1, 2, 3]
    ])
print(type(array3))

<class 'numpy.ndarray'>


In [21]:
print(array3.shape)

(1, 3)


In [23]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [25]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [29]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3) # 자동 형변환
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [30]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype(np.float64)
print(array_float, array_float.dtype)


[1. 2. 3.] float64


In [31]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [32]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


In [33]:
array1 = np.arange(10)
array2 = np.zeros((3, 2), dtype='int32')
array3 = np.ones((3, 2))

In [34]:
print(array1, array2, array3)

[0 1 2 3 4 5 6 7 8 9] [[0 0]
 [0 0]
 [0 0]] [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [36]:
array1 = array1.reshape(2, 5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
array2 = array2.reshape(-1, 3)
array2

array([[0, 0, 0],
       [0, 0, 0]])

In [42]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [43]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [44]:
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [45]:
array1 = np.arange(10)
print(f'array1: \n {array1}')

array2 = array1.reshape(5, 2)
print(f'array2:\n {array2}')

array1: 
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [48]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print(array2)

array3 = array1.reshape(5, -1)
print(array3.shape)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
(5, 2)


In [56]:
array1 = np.arange(10)
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print(f'array3\n {array3d.tolist()}')
print(array3d)

array5 = array3d.reshape(-1, 1)
print(array5.tolist())
print(array5.shape)
array6 = array1.reshape(-1 , 1)
print(array6.tolist())
print(array6.shape)

array3
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)
