In [ ]:
import pandas as pd
pd.__version__

In [ ]:
titanic_df = pd.read_csv('../data/train.csv')
print(type(titanic_df))

In [ ]:
titanic_df

In [ ]:
print(titanic_df.shape)

In [ ]:
titanic_df.head()

In [ ]:
titanic_df.tail()

In [ ]:
display(titanic_df.head(3))
titanic_df.tail(3)

In [ ]:
pd.set_option("display.max_rows", 1000)
pd.set_option("display.max_colwidth", 100)
pd.set_option('display.max_columns', 100)

In [ ]:
titanic_df

In [ ]:
titanic_df.shape

In [ ]:
dict1 = {'Name' : ['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobeom'],
         'Year' : [2011, 2016, 2015, 2015],
         'Gender': ['Male', 'Female', 'Male', 'Male']}
data_df = pd.DataFrame(dict1)
print(data_df)
print("#"*30)

data_df = pd.DataFrame(dict1, columns=["Name", "Year", "Gender", "Age"])
print(data_df)
print("#"*30)

data_df = pd.DataFrame(dict1, index=['one', 'two', 'three', 'four'])
print(data_df)
print('#'*30)

In [ ]:
print(titanic_df.columns)
print(titanic_df.index)
print(titanic_df.index.values)

In [ ]:
titanic_df.info()

In [ ]:
titanic_df.info()

In [ ]:
titanic_df.describe()

In [ ]:
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

In [ ]:
titanic_df['Pclass'].head()

In [ ]:
titanic_df_pclass = titanic_df['Pclass']
print(type(titanic_df_pclass))

In [ ]:
print(titanic_df.shape[0])
print(titanic_df['Embarked'].value_counts())
print(titanic_df['Embarked'].value_counts(dropna=False))

In [ ]:
titanic_df[['Pclass', 'Embarked']].value_counts()

In [ ]:
import numpy as np
col_name1 = ['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)

print(array1.shape)
df_list1 = pd.DataFrame(list1, columns=col_name1)
print(df_list1)
df_array1 = pd.DataFrame(array1, columns=col_name1)
print(df_array1)

In [ ]:
col_name2 = ['col1', 'col2', 'col3']
list2 = [[1, 2, 3],
         [11, 12, 13]]
array2 = np.array(list2)
print(array2.shape)
df_list2 = pd.DataFrame(list2, columns=col_name2)
print(df_list2)

In [ ]:
dict = {'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}
df_dict = pd.DataFrame(dict)
print(df_dict)

In [ ]:
array3 = df_dict.values
print(array3.shape)
print(array3)

In [ ]:
list3 = df_dict.values.tolist()
print(type(list3))
print(list3)

In [ ]:
dict3 = df_dict.to_dict('list')
print(type(dict3))
print(dict3)

In [ ]:
titanic_df['Age_0'] = 0
titanic_df.head(3)

In [ ]:
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch']+1
titanic_df.head(3)

In [ ]:
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

In [6]:
import pandas as pd

titanic_df = pd.read_csv("../data/train.csv")
titanic_df.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [7]:
titanic_df.reset_index()

index  PassengerId  Survived  Pclass  \
0        0            1         0       3   
1        1            2         1       1   
2        2            3         1       3   
3        3            4         1       1   
4        4            5         0       3   
..     ...          ...       ...     ...   
886    886          887         0       2   
887    887          888         1       1   
888    888          889         0       3   
889    889          890         1       1   
890    890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 13 columns]

In [8]:
titanic_df = pd.read_csv('../data/train.csv')
indexes = titanic_df.index
print(indexes)
print(indexes.values)

RangeIndex(start=0, stop=891, step=1)
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 

In [9]:
type(indexes.values)

numpy.ndarray

In [12]:
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [16]:
series_fair = titanic_df['Fare']
print(series_fair.max())
print(series_fair.sum())
print(sum(series_fair))
print((series_fair + 3).head(3))

512.3292
28693.9493
28693.949299999967
0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


In [19]:
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64


index  PassengerId  Survived  Pclass  \
0      0            1         0       3   
1      1            2         1       1   
2      2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [24]:
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print(type(value_counts), value_counts.shape)

new_value_counts_01 = value_counts.reset_index(inplace=False)
print(new_value_counts_01)
print(type(new_value_counts_01), new_value_counts_01.shape)

new_value_counts_02 = value_counts.reset_index(drop=True, inplace=False)
print(new_value_counts_02)
print(type(new_value_counts_02), new_value_counts_02.shape)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64
<class 'pandas.core.series.Series'> (3,)
   Pclass  count
0       3    491
1       1    216
2       2    184
<class 'pandas.core.frame.DataFrame'> (3, 2)
0    491
1    216
2    184
Name: count, dtype: int64
<class 'pandas.core.series.Series'> (3,)


In [48]:
series = titanic_df['Name']
print(series.head(3))
print(type(series), series.shape)

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
Name: Name, dtype: object
<class 'pandas.core.series.Series'> (891,)


In [49]:
filtered_df = titanic_df[['Name', 'Age']]
display(filtered_df.head(3))
print(type(filtered_df), filtered_df.shape)

Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0

<class 'pandas.core.frame.DataFrame'> (891, 2)


In [51]:
one_col_df = titanic_df[['Name']]
display(one_col_df.head(3))
print(one_col_df.shape, type(one_col_df))

Name
0                            Braund, Mr. Owen Harris
1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                             Heikkinen, Miss. Laina

(891, 1) <class 'pandas.core.frame.DataFrame'>


In [52]:
titanic_df[0:2]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [53]:
titanic_df[titanic_df['Pclass'] == 3].head(3)

PassengerId  Survived  Pclass                      Name     Sex   Age  \
0            1         0       3   Braund, Mr. Owen Harris    male  22.0   
2            3         1       3    Heikkinen, Miss. Laina  female  26.0   
4            5         0       3  Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket   Fare Cabin Embarked  
0      1      0         A/5 21171  7.250   NaN        S  
2      0      0  STON/O2. 3101282  7.925   NaN        S  
4      0      0            373450  8.050   NaN        S

In [54]:
data = {'Name' : ['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobeom'],
        'Year' : [2011, 20216, 2015, 2015],
        'Gender': ['Male', 'Famele', 'Male', 'Male']}
data_df = pd.DataFrame(data, index=['one', 'two', 'three', 'four'])
data_df

Name   Year  Gender
one     Chulmin   2011    Male
two    Eunkyung  20216  Famele
three  Jinwoong   2015    Male
four    Soobeom   2015    Male

In [55]:
data_df.iloc[0, 0]

'Chulmin'

In [57]:
print(data_df.iloc[1, 0])
print(data_df.iloc[2, 1])

Eunkyung
2015


In [58]:
print(data_df.iloc[:])
print(data_df.iloc[:, :])

           Name   Year  Gender
one     Chulmin   2011    Male
two    Eunkyung  20216  Famele
three  Jinwoong   2015    Male
four    Soobeom   2015    Male
           Name   Year  Gender
one     Chulmin   2011    Male
two    Eunkyung  20216  Famele
three  Jinwoong   2015    Male
four    Soobeom   2015    Male


In [59]:
data_df.loc['one', 'Name']

'Chulmin'

In [60]:
data_df.iloc[0:1, 0]

one    Chulmin
Name: Name, dtype: object

In [62]:
data_df.loc['one': 'two', 'Name']

one     Chulmin
two    Eunkyung
Name: Name, dtype: object